########################################################################
#                       Rust Style Configuration                       #
#                                                                      #
# Since most of rustfmt's configuration options are still unstable, we #
# use the nightly rustfmt. You will need to configure your editor to   #
# format with `cargo +nightly fmt` rather than `cargo fmt`.            #
#                                                                      #
# See <https://rust-lang.github.io/rustfmt/?version=v1.8.0>            #
########################################################################

# Stable as of current nightly

disable_all_formatting = false
edition = "2021"
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 81
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# Still unstable

binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
doc_comment_code_block_width = 100
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_line_overflow = false
error_on_unformatted = true
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = false
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
generated_marker_line_search_limit = 5
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
ignore = []
imports_indent = "Block"
imports_granularity = "Crate"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
required_version = "1.8.0"
show_parse_errors = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 8
struct_lit_single_line = true
style_edition = "2021"
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
where_single_line = true
wrap_comments = true
