########################################################################
#                     Rust Toolchain Configuration                     #
#                                                                      #
# This file governs the Rust toolchain used to build and operate the   #
# project.                                                             #
########################################################################

[toolchain]
channel = "1.85.0"
profile = "default"
components = [
	"clippy",
	"rustfmt",
	"rust-src",
]
# channel = "nightly"
# components = [
# 	"miri",
# ]
